In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./data.csv")

In [3]:
df

,Unnamed: 0,aiddata_id,aiddata_2_id,year,donor,recipient,commitment_amount_usd_constant,coalesced_purpose_code,coalesced_purpose_name
0,1,2.414478e+06,NaN,1977,Saudi Arabia,India,348718518.0,23030,Power generation/renewable sources
1,2,2.414509e+06,NaN,1977,Saudi Arabia,Brazil,191647004.0,23040,Electrical transmission/ distribution
2,3,2.414635e+06,NaN,1983,Saudi Arabia,India,79371799.0,21030,Rail transport
3,4,2.414665e+06,NaN,1984,Saudi Arabia,Taiwan,212202942.0,21030,Rail transport
4,5,2.414667e+06,NaN,1984,Saudi Arabia,Korea,134511154.0,21040,Water transport
5,6,2.414684e+06,NaN,1985,Saudi Arabia,India,128074768.0,23000,"Energy generation and supply, combinations of ..."
6,7,2.414760e+06,NaN,1987,Saudi Arabia,India,72707674.0,21040,Water transport
7,8,2.414840e+06,NaN,1993,Kuwait,Cyprus,25461230.0,21020,Road transport
8,9,2.415076e+06,NaN,1996,Kuwait,Lithuania,21381183.0,23050,Gas distribution
9,10,2.415206e+06,NaN,1998,Kuwait,India,1107033.0,21020,Road transport
10,11,2.426999e+06,NaN,1978,Kuwait,India,103885863.0,23000,"Energy generation and supply, combinations of ..."
11,12,2.427052e+06,NaN,1976,Kuwait,India,193588873.0,23030,Power generation/renewable sources
12,13,2.427058e+06,NaN,1976,Kuwait,Thailand,12905925.0,23040,Electrical transmission/ distribution
13,14,2.427115e+06,NaN,2001,Kuwait,Slovak Republic,1219994.0,14020,Water supply and sanitation - large systems
14,15,2.428296e+06,NaN,1992,Kuwait,Cyprus,6635123.0,21020,Road transport
15,16,2.428502e+06,NaN,1989,Kuwait,India,43493083.0,31320,Fishery development
16,17,2.428506e+06,NaN,1988,Kuwait,Cyprus,16145060.0,21020,Road transport
17,18,2.428566e+06,NaN,1988,Kuwait,Cyprus,27769503.0,14020,Water supply and sanitation - large systems
18,19,2.428587e+06,NaN,1986,Kuwait,Cyprus,30606432.0,21020,Road transport
19,20,2.428601e+06,NaN,1986,Kuwait,India,53561256.0,23030,Power generation/renewable sources
20,21,2.428623e+06,NaN,1984,Kuwait,Cyprus,27051193.0,14040,River development
21,22,2.428652e+06,NaN,1983,Kuwait,India,133092433.0,32220,Mineral/Metal prospection and exploration
22,23,2.428882e+06,NaN,1982,Kuwait,India,131175647.0,32120,Industrial development
23,24,2.428885e+06,NaN,1982,Kuwait,Thailand,50452172.0,23030,Power generation/renewable sources
24,25,2.428888e+06,NaN,1983,Kuwait,Cyprus,21878208.0,21020,Road transport
25,26,2.428969e+06,NaN,1981,Kuwait,India,83971160.0,43010,Multisector aid
26,27,2.428974e+06,NaN,1981,Kuwait,Thailand,65310902.0,23020,Power generation/non-renewable sources
27,28,2.429003e+06,NaN,1981,Kuwait,India,149282062.0,23020,Power generation/non-renewable sources
28,29,2.429034e+06,NaN,1979,Kuwait,Thailand,59307807.0,23000,"Energy generation and supply, combinations of ..."
29,30,2.429037e+06,NaN,1980,Kuwait,Cyprus,23153412.0,14040,River development
...,...,...,...,...,...,...,...,...,...
98510,98511,9.060009e+11,NaN,2013,Portugal,Chile,109.0,16061,Culture and recreation
98511,98512,9.060009e+11,NaN,2013,Poland,Brazil,63571.0,11420,Higher education
98512,98513,9.060009e+11,NaN,2013,Greece,India,24288.0,11420,Higher education
98513,98514,9.060009e+11,NaN,2013,Poland,Brazil,1657.0,11420,Higher education
98514,98515,9.060009e+11,NaN,2013,Poland,Brazil,4141.0,11420,Higher education
98515,98516,9.060009e+11,NaN,2013,Greece,Brazil,25253.0,11420,Higher education
98516,98517,9.060009e+11,NaN,2013,Portugal,Brazil,17651.0,24020,Monetary institutions
98517,98518,9.060009e+11,NaN,2013,Slovak Republic,Chile,2296.0,11420,Higher education
98518,98519,9.060009e+11,NaN,2013,Greece,Chile,1671.0,11420,Higher education
98519,98520,9.060009e+11,NaN,2013,Portugal,Brazil,197649.0,43082,Research/scientific institutions
98520,98521,9.060009e+11,NaN,2013,New Zealand,India,7911.0,11420,Higher education
98521,98522,9.060009e+11,NaN,2013,New Zealand,Brazil,81580.0,24030,Formal sector financial intermediaries
98522,98523,9.060009e+11,NaN,2013,New Zealand,Brazil,52072.0,11420,Higher education
98523,98524,9.060009e+11,NaN,2013,New Zealand,Chile,73769.0,15110,Economic and development policy/planning
98524,98525,9.060009e+11,NaN,2013,New Zealand,South Africa,112232.0,91010,Administrative costs
98525,98526,9.060009e+11,NaN,2013,New Zealand,India,954657.0,16030,Housing policy and administrative management
98526,98527,9.060009e+11,NaN,2013,New Zealand,Chile,245607.0,11420,Higher education
98527,98528,9.060009e+11,NaN,2013,New Zealand,Colombia,244739.0,31100,"Agriculture, combinations of purposes in Agric..."
98528,98529,9.060009e+11,NaN,2013,New Zealand,South Africa,27772.0,11420,Higher education
98529,98530,9.060009e+11,NaN,2013,New Zealand,South Africa,77240.0,15110,Economic and development policy/planning
98530,98531,9.060009e+11,NaN,2013,New Zealand,Thailand,60751.0,11320,Secondary education
98531,98532,9.060009e+11,NaN,2013,Czech Republic,Brazil,4001.0,11320,Secondary education
98532,98533,9.060009e+11,NaN,2013,Czech Republic,Thailand,127.0,15110,Economic and development policy/planning
98533,98534,9.060009e+11,NaN,2013,Czech Republic,Chile,3678.0,15110,Economic and development policy/planning
98534,98535,9.060009e+11,NaN,2013,Czech Republic,South Africa,2382.0,11105,"Education, level unspecified, purpose unspecif..."
98535,98536,9.060009e+11,NaN,2013,Czech Republic,Colombia,51840.0,11420,Higher education
98536,98537,9.060009e+11,NaN,2013,Czech Republic,India,35380.0,72010,Material relief assistance and services
98537,98538,9.060009e+11,NaN,2013,Czech Republic,India,11930.0,11420,Higher education
98538,98539,9.060009e+11,NaN,2013,Czech Republic,Brazil,6669.0,16010,Social/ welfare services
98539,98540,9.060009e+11,NaN,2013,Czech Republic,Chile,7145.0,11120,Education facilities and training

In [4]:
data_agg = df.groupby(['coalesced_purpose_code'], as_index=False).agg({"commitment_amount_usd_constant": "sum"})

In [5]:
data_agg.nlargest(5, 'commitment_amount_usd_constant')

                     coalesced_purpose_name  commitment_amount_usd_constant
33                            Air transport                    3.981248e+10
321                          Rail transport                    2.049887e+10
224                  Industrial development                    1.973854e+10
303  Power generation/non-renewable sources                    1.512861e+10
318            RESCHEDULING AND REFINANCING                    1.479750e+10

In [6]:
purpose_list = [21030,"Rail transport","Industrial development","Power generation/non-renewable sources","RESCHEDULING AND REFINANCING"]

In [7]:
data_r = df[["recipient","donor","coalesced_purpose_name","commitment_amount_usd_constant"]]

In [8]:
data_r.coalesced_purpose_name = data_r.coalesced_purpose_name.str.lower()

C:\Users\tv655\Anaconda3\lib\site-packages\pandas\core\generic.py:4405: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [9]:
data_r

,recipient,donor,coalesced_purpose_name,commitment_amount_usd_constant
0,India,Saudi Arabia,power generation/renewable sources,348718518.0
1,Brazil,Saudi Arabia,electrical transmission/ distribution,191647004.0
2,India,Saudi Arabia,rail transport,79371799.0
3,Taiwan,Saudi Arabia,rail transport,212202942.0
4,Korea,Saudi Arabia,water transport,134511154.0
5,India,Saudi Arabia,"energy generation and supply, combinations of ...",128074768.0
6,India,Saudi Arabia,water transport,72707674.0
7,Cyprus,Kuwait,road transport,25461230.0
8,Lithuania,Kuwait,gas distribution,21381183.0
9,India,Kuwait,road transport,1107033.0
10,India,Kuwait,"energy generation and supply, combinations of ...",103885863.0
11,India,Kuwait,power generation/renewable sources,193588873.0
12,Thailand,Kuwait,electrical transmission/ distribution,12905925.0
13,Slovak Republic,Kuwait,water supply and sanitation - large systems,1219994.0
14,Cyprus,Kuwait,road transport,6635123.0
15,India,Kuwait,fishery development,43493083.0
16,Cyprus,Kuwait,road transport,16145060.0
17,Cyprus,Kuwait,water supply and sanitation - large systems,27769503.0
18,Cyprus,Kuwait,road transport,30606432.0
19,India,Kuwait,power generation/renewable sources,53561256.0
20,Cyprus,Kuwait,river development,27051193.0
21,India,Kuwait,mineral/metal prospection and exploration,133092433.0
22,India,Kuwait,industrial development,131175647.0
23,Thailand,Kuwait,power generation/renewable sources,50452172.0
24,Cyprus,Kuwait,road transport,21878208.0
25,India,Kuwait,multisector aid,83971160.0
26,Thailand,Kuwait,power generation/non-renewable sources,65310902.0
27,India,Kuwait,power generation/non-renewable sources,149282062.0
28,Thailand,Kuwait,"energy generation and supply, combinations of ...",59307807.0
29,Cyprus,Kuwait,river development,23153412.0
...,...,...,...,...
98510,Chile,Portugal,culture and recreation,109.0
98511,Brazil,Poland,higher education,63571.0
98512,India,Greece,higher education,24288.0
98513,Brazil,Poland,higher education,1657.0
98514,Brazil,Poland,higher education,4141.0
98515,Brazil,Greece,higher education,25253.0
98516,Brazil,Portugal,monetary institutions,17651.0
98517,Chile,Slovak Republic,higher education,2296.0
98518,Chile,Greece,higher education,1671.0
98519,Brazil,Portugal,research/scientific institutions,197649.0
98520,India,New Zealand,higher education,7911.0
98521,Brazil,New Zealand,formal sector financial intermediaries,81580.0
98522,Brazil,New Zealand,higher education,52072.0
98523,Chile,New Zealand,economic and development policy/planning,73769.0
98524,South Africa,New Zealand,administrative costs,112232.0
98525,India,New Zealand,housing policy and administrative management,954657.0
98526,Chile,New Zealand,higher education,245607.0
98527,Colombia,New Zealand,"agriculture, combinations of purposes in agric...",244739.0
98528,South Africa,New Zealand,higher education,27772.0
98529,South Africa,New Zealand,economic and development policy/planning,77240.0
98530,Thailand,New Zealand,secondary education,60751.0
98531,Brazil,Czech Republic,secondary education,4001.0
98532,Thailand,Czech Republic,economic and development policy/planning,127.0
98533,Chile,Czech Republic,economic and development policy/planning,3678.0
98534,South Africa,Czech Republic,"education, level unspecified, purpose unspecif...",2382.0
98535,Colombia,Czech Republic,higher education,51840.0
98536,India,Czech Republic,material relief assistance and services,35380.0
98537,India,Czech Republic,higher education,11930.0
98538,Brazil,Czech Republic,social/ welfare services,6669.0
98539,Chile,Czech Republic,education facilities and training,7145.0

In [10]:
data_r = data_r[data_r['coalesced_purpose_code'].isin([purpose.lower() for purpose in purpose_list])]

In [11]:
data_r = data_r.groupby(['recipient','donor','coalesced_purpose_code'], as_index=False).agg({"commitment_amount_usd_constant": "sum"})

In [12]:
data_r

,recipient,donor,coalesced_purpose_name,commitment_amount_usd_constant
0,Australia,United States,air transport,2.414954e+09
1,Australia,United States,industrial development,8.970500e+06
2,Australia,United States,rail transport,6.837255e+07
3,Austria,United States,air transport,7.699085e+08
4,Belgium,United States,air transport,1.843462e+08
5,Brazil,Austria,industrial development,5.167098e+06
6,Brazil,Belgium,industrial development,1.152172e+06
7,Brazil,Belgium,rescheduling and refinancing,9.530131e+07
8,Brazil,Canada,industrial development,2.974866e+07
9,Brazil,Canada,power generation/non-renewable sources,6.054352e+06
10,Brazil,Canada,rail transport,1.769300e+04
11,Brazil,France,rail transport,1.112452e+08
12,Brazil,France,rescheduling and refinancing,3.917663e+07
13,Brazil,Germany,industrial development,8.235516e+07
14,Brazil,Germany,rail transport,3.974931e+07
15,Brazil,Germany,rescheduling and refinancing,3.838057e+08
16,Brazil,Ireland,industrial development,7.747500e+04
17,Brazil,Italy,industrial development,7.806570e+05
18,Brazil,Italy,power generation/non-renewable sources,1.567700e+04
19,Brazil,Japan,air transport,1.001650e+05
20,Brazil,Japan,industrial development,3.019423e+08
21,Brazil,Japan,rail transport,1.249130e+06
22,Brazil,Japan,rescheduling and refinancing,1.160096e+08
23,Brazil,Korea,industrial development,1.232070e+05
24,Brazil,Norway,industrial development,8.083100e+04
25,Brazil,Portugal,industrial development,5.001900e+04
26,Brazil,Portugal,rail transport,9.365910e+05
27,Brazil,Spain,air transport,1.406770e+05
28,Brazil,Spain,industrial development,1.110417e+06
29,Brazil,Spain,rail transport,1.403750e+05
...,...,...,...,...
379,Thailand,Germany,power generation/non-renewable sources,5.431390e+07
380,Thailand,Germany,rail transport,1.623912e+08
381,Thailand,Germany,rescheduling and refinancing,5.898800e+05
382,Thailand,Italy,rail transport,1.488852e+06
383,Thailand,Japan,air transport,2.648320e+09
384,Thailand,Japan,industrial development,1.348022e+09
385,Thailand,Japan,power generation/non-renewable sources,2.236434e+07
386,Thailand,Japan,rail transport,5.249206e+09
387,Thailand,Korea,air transport,5.233500e+04
388,Thailand,Korea,industrial development,1.096198e+06
389,Thailand,Korea,power generation/non-renewable sources,1.094230e+05
390,Thailand,Korea,rail transport,1.119080e+05
391,Thailand,Kuwait,power generation/non-renewable sources,6.531090e+07
392,Thailand,Netherlands,industrial development,1.381313e+07
393,Thailand,Norway,air transport,6.050200e+04
394,Thailand,Norway,industrial development,6.304303e+06
395,Thailand,Saudi Arabia,power generation/non-renewable sources,9.567654e+07
396,Thailand,Spain,industrial development,3.243500e+04
397,Thailand,Sweden,industrial development,1.325932e+07
398,Thailand,Switzerland,power generation/non-renewable sources,6.063103e+06
399,Thailand,United Kingdom,industrial development,1.231750e+08
400,Thailand,United Kingdom,rail transport,1.287469e+07
401,Thailand,United States,air transport,1.378790e+09
402,Thailand,United States,industrial development,1.460262e+09
403,Thailand,United States,power generation/non-renewable sources,6.196218e+08
404,Thailand,United States,rail transport,1.874200e+04
405,United Arab Emirates,Austria,industrial development,7.609720e+05
406,United Arab Emirates,Japan,industrial development,6.992130e+05
407,United Arab Emirates,United States,air transport,5.225530e+05
408,United Kingdom,United States,air transport,9.573440e+08

In [19]:
data_f = data_r.groupby(["recipient","donor"])['coalesced_purpose_name'].apply(list)

In [22]:
data_f.to_csv("./final.csv")

In [23]:
for purpose in purpose_list:
    data_r[data_r['coalesced_purpose_code'] == purpose].to_csv("./"+str(purpose)+".csv")

FileNotFoundError: [Errno 2] No such file or directory: './Power generation/non-renewable sources.csv'

In [ ]:
data_r = data_r.groupby(['recipient','donor'], as_index=False).agg({"commitment_amount_usd_constant": "sum"})

In [ ]:
donor = data_r['donor'].unique()

In [ ]:
recipient = data_r['recipient'].unique()

In [ ]:
list_ = list(donor) + list(recipient)

In [ ]:
my_set = set(list_)
my_new_list = list(my_set)

In [ ]:
my_new_list

In [ ]:
import numpy as np
np.savetxt("countries.csv", my_new_list , delimiter=",", fmt='%s', header="countries")

In [ ]:
data_r

In [28]:
import csv
with open('final.csv', newline='') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=' ', quotechar='|')
    for row in spamreader:
        row